<?php
/**
 * @file
 * A module that inserts into the pantry all products of a list.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function buy_list_help($path, $arg) {
  switch ($path) {
    case "admin/help#buy_list":
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("The Buy List module inserts into the user pantry all products os a given list") . '</p>';
      return $output;
  }
}

function buy_list_extract_products($node) {
	if ($node->type == 'lista') {
		$id_list = $node->nid['0']['value'];
		$id_list_products = db_fetch_array(db_query("SELECT field_productos_compra_value FROM {drupalis_field_data_field_productos_compra} WHERE entity_id = %d", $id_list));
		
	}
}
